### ISSUE TITLE
What is OmniSwift and where do I get it?

### ISSUE THREAD

**Issue by drock07** [CooperCorona/Voronoi#1]
I was really excited to see a swift voronoi diagram framework and cloned the repo right away! However, I can't build it because it has a dependency on OmniSwift.

So what is OmniSwift? How do I get it?

**Comment by CooperCorona** [comment]
Whoops! OmniSwift is a framework I've built up over the years. I need to
make the repository public. Sorry for the inconvenience!

**Comment by CooperCorona** [comment]
Here's the link to OmniSwift:
https://github.com/CooperCorona/OmniSwift

If you find any bugs or notice areas in need of improvement in either
repository, please make an issue on the Github page. I hope you find
Voronoi useful!

**Comment by drock07** [comment]
Thanks for the quick response! I'm excited to try out both frameworks.
